# Generated by Django 5.2.8 on 2025-12-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Телеграм чата'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код подключения'),
        ),
    ]
