# Generated by Django 5.2.8 on 2025-12-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_telegram_chat_id_customuser_telegram_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bot_category',
            field=models.CharField(choices=[('logic', 'Логика'), ('math', 'Математика'), ('spatial', 'Пространственное мышление'), ('memory', 'Память')], default='logic', max_length=20, verbose_name='Категория для тренировок в Telegram'),
        ),
    ]
