# Generated by Django 5.2.8 on 2025-12-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_bot_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('kk', 'Qazaqsha'), ('en', 'English')], default='ru', max_length=5, verbose_name='Язык / Language'),
        ),
    ]
