# Generated by Django 5.2.8 on 2025-11-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_usertestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст ответа'),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст ответа'),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст ответа'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_kk',
            field=models.TextField(null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AddField(
            model_name='test',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='test',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='test',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='test',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название теста'),
        ),
        migrations.AddField(
            model_name='test',
            name='title_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название теста'),
        ),
        migrations.AddField(
            model_name='test',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название теста'),
        ),
    ]
