# Generated by Django 5.2.8 on 2025-12-02 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_botresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usertestresult',
            options={},
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('logic', 'Логика'), ('math', 'Математика'), ('spatial', 'Пространственное мышление'), ('memory', 'Память')], default='logic', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Изображение (Карточка)'),
        ),
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='test_covers/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='usertestresult',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='Анализ ИИ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='description_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='test',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='title_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usertestresult',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usertestresult',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usertestresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.test'),
        ),
        migrations.AlterField(
            model_name='usertestresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quiz.usertestresult')),
                ('selected_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.answer')),
            ],
        ),
        migrations.DeleteModel(
            name='BotResult',
        ),
    ]
