# Generated by Django 5.2.8 on 2025-12-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions_count',
            field=models.IntegerField(default=10, verbose_name='Кол-во вопросов (N)'),
        ),
        migrations.AddField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(default=0, help_text='0 - без ограничений', verbose_name='Время на тест (минуты)'),
        ),
    ]
