# Generated by Django 5.2.8 on 2025-12-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_botresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_time',
            field=models.IntegerField(default=60, help_text='Лимит времени конкретно на этот вопрос.', verbose_name='Время на ответ (сек)'),
        ),
        migrations.AddField(
            model_name='question',
            name='exposure_time',
            field=models.IntegerField(default=0, help_text='Сколько секунд показывать картинку (для тестов на память). 0 - показывать всегда.', verbose_name='Время показа (сек)'),
        ),
    ]
