# Generated by Django 5.2.8 on 2025-12-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_testinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestresult',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.test'),
        ),
    ]
