# Generated by Django 5.2.8 on 2025-12-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('logic', 'Логика'), ('math', 'Математика'), ('spatial', 'Пространственное мышление'), ('memory', 'Память'), ('Multi_table', 'Таблица умножения')], default='logic', max_length=20, verbose_name='Категория'),
        ),
    ]
