# Generated by Django 5.2.8 on 2026-01-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_audience',
            field=models.CharField(choices=[('user', 'Для пользователей (самопознание)'), ('recruiter', 'Для рекрутеров (оценка кандидатов)'), ('both', 'Для всех')], default='both', help_text='Для кого предназначен этот тест: для пользователей (самопознание) или для рекрутеров (оценка кандидатов)', max_length=10, verbose_name='Аудитория теста'),
        ),
    ]
